### ISSUE TITLE
maim doesn't work while dmenu is already active

### ISSUE THREAD

**Issue by TheYellowArchitect** [naelstrof/maim#287] opened 2023-11-19 12:40 UTC
I use dwm with the following config line
`{ ShiftMask,	XK_Print, spawn, SHCMD("maim pic-full-$(date '+%y%m%d-%H%M-%S').png") },`

I do not have any alias to `maim` or `dmenu`

If I open dmenu and dmenu awaits for input (so it's active), the above command doesn't work.

**Comment by 2084x** [comment] 2024-04-02 09:50
I believe this is because dmenu takes control of all key input when open. you should notice that none of your other dwm binds work when dmenu is running either. this is really a dmenu 'issue', rather than a maim one.

**Comment by foxpy** [comment] 2024-04-30 07:48
The issue is out of scope of maim, since in this case maim is never being run in a first place.
Also maim doesn't handle keyboard bindings, and it really shouldn't do that.

I would suggest various approaches to this issue:
- using a delayed launch of maim, e.g. `SHCMD("sleep 5 && maim pic-full-$(date '+%y%m%d-%H%M-%S').png")`, pressing your binding, opening dmenu and then waiting for maim to launch;
- somehow patching dmenu and/or dwm so your binding still works when dmenu is active;
- switching to another desktop environment where this issue is not present;
- ignoring this issue alltogether :)

**Closed by foxpy** 2024-04-30 07:48 UTC
