### ISSUE TITLE
[Feature Request] Capturing the last video buffer before running maim

### ISSUE THREAD

**Issue by OnionHat** [naelstrof/maim#232] opened 2021-06-07 00:46 UTC
This is a features request for capturing a selection of the last video buffer. This means that when running maim -s everything on the display stops; animation, video etc. This is like when using win+shift+s on windows.

**Comment by foxpy** [comment] 2021-06-07 02:24
Duplicate of #193

**Comment by OnionHat** [comment] 2021-06-07 04:40
Would it not be better to have a flag for it and not a work around?

**Comment by foxpy** [comment] 2021-06-07 07:21
To be honest I would love to see this feature in maim as well.
But, please, read #193 again, and this time carefully.
Especially this [bit](https://github.com/naelstrof/maim/issues/193#issuecomment-571904450).
If you don't like the workaround provided, you could work on the "freeze" program I have described [here](https://github.com/naelstrof/maim/issues/193#issuecomment-589629243).
This solution is much cleaner.

Also, this issue is definitely a duplicate of #193, as you are asking for the same feature.

**Comment by naelstrof** [comment] 2021-06-15 02:20
> Would it not be better to have a flag for it and not a work around?

I don't think so, in the README there's an example that works fine to freeze a frame and to crop it.
You could even make it more advanced by having it open into GIMP/Krita, so you can not only crop it, you could add effects, arrows, and text.
Maim is meant to take a picture of the desktop, and to do it well. Cropping is a post-process that is served great by many other apps.

**Closed by naelstrof** 2021-06-15 02:20 UTC
