### ISSUE TITLE
blank screenshot 

### ISSUE THREAD

**Issue by eoli3n** [naelstrof/maim#71] opened 2017-01-17 17:13 UTC
I don't know if it's slop or maim issue.

I'm using i3wm, when i "click" in a window with ``maim -s`` screenshot is in right size... but completely empty.

Selecting by mouse sliding works perfectly.

![alt](http://ptpb.pw/VUaF.png)

**Comment by alezost** [comment] 2017-01-17 19:02
I recall I had the same problem in the past but it began to work
since... I don't remember what version.  Currently I use `3.4.47`, what
`maim --version` do you have?

**Comment by eoli3n** [comment] 2017-01-17 20:56
maim v3.4.47

**Comment by alezost** [comment] 2017-01-18 08:44
@Streetwalrus says it's [related to Xorg 1.19](https://github.com/naelstrof/maim/issues/70#issuecomment-273285302).  I still use Xorg 1.18, and "it works for me", so it's probably the root of the issue indeed.

**Comment by KeyboardFire** [comment] 2017-01-19 03:14
I can confirm that this issue recently started happening to me as well—selecting with click and drag and full screen screenshots work perfectly, but clicking a window results in a blank image. I am also on Arch with i3 and recently updated Xorg to 1.19.

**Comment by 676339784** [comment] 2017-01-23 05:16
Unsure if this applies to you guys, but i find that `maim -s` and then clicking/hitting Enter only breaks on urxvt. Doing the same works in Firefox, as an example.

**Comment by Streetwalrus** [comment] 2017-01-23 06:15
It breaks on chromium and telegram for me as well, haven't tried anything else.

**Comment by rhssk** [comment] 2017-01-28 19:13
Same problem here with maim 3.4.47. `-s` + click gets window partially or not at all (just black background) while wither `-s` + mouse slide or no `-s` at all works perfectly. Maybe this is an issue with [slop](https://github.com/naelstrof/slop)?

**Comment by onodera-punpun** [comment] 2017-01-28 19:42
Exact same problem here rhssk.

With click: https://punpun.xyz/bznv.png
with drag: https://punpun.xyz/puq1.png

**Comment by Streetwalrus** [comment] 2017-01-28 19:43
We've already established that it's Xorg 1.19 that is at fault, not slop nor maim.

**Comment by onodera-punpun** [comment] 2017-01-28 19:44
@Streetwalrus Is this really xorg though? I'm writing a screenshot tool for fun (and partly because of this issue), and my program does window selection scrots just fine.

**Comment by naelstrof** [comment] 2017-01-28 20:29
OK since I found out Wayland literally doesn't support screen shots. Instead of porting maim to Wayland I'm going to rewrite maim to not use imlib2.
Meanwhile a temporary fix would be to not use the window ID flag. (Maim uses it by default when selecting Windows) This might involve writing a tiny script that chains slop into maim's geometry flag.

**Comment by dmitry-saritasa** [comment] 2017-02-15 00:14
Would be nice to support wayland.

**Comment by naelstrof** [comment] 2017-02-15 00:55
It will have limited support. I have to support each individual compositor, and Wayland is too secure to allow for window screenshots..

**Comment by Lemmmy** [comment] 2017-02-22 22:19
Unfortunately the latest versions of several packages on my system including my DE require Xorg 1.19 now, so I can't keep it downgraded, meaning it's time to move on from maim for me...

**Comment by naelstrof** [comment] 2017-02-22 22:47
I've fixed the issue in the release candidate. You can find it here with some basic instructions on how to install: https://github.com/naelstrof/maim/tree/maim-release-candidate

The interface has changed dramatically, there's a few bugs left to squash, and help/man pages haven't been written yet. Up to you to switch though Lemmmy, good luck!

**Comment by naelstrof** [comment] 2017-02-23 12:02
Ok, release candidate was merged. New tag released: https://github.com/naelstrof/maim/releases/tag/v4.4.47

It works fine from what I tested. Sorry it took so long!

**Comment by naelstrof** [comment] 2017-02-27 02:00
I'm going to close this thread because I believe the issue is resolved.

**Closed by naelstrof** 2017-02-27 02:00 UTC
