### ISSUE TITLE
Yakuake seen as transparent block

### ISSUE THREAD

**Issue by enui** [naelstrof/maim#113] opened 2017-09-13 03:27 UTC
Yakuake, a drop-down terminal, is set up to cover the top half of my screen when activated. When hidden, if I try to take a selection screenshot the area where yakuake would be is fully transparent in the resulting image. It only happens with selections. If yakuake is not running or was hidden on another display the issue is gone. I hope screenshot can explain best.

I don't know if this is considered an issue with maim, but it took me awhile to figure out, and I couldn't find any information on it. I thought it was related to #102 and #111, as I had very similar issues also.

Command:
`maim -s -b 5 | xclip -selection clipboard -t image/png`

`Yakuake v3.0.4`
`Maim v5.4.66`

These are both the same region captured,
with:
![yakuake](https://user-images.githubusercontent.com/30557958/30358280-2383bbfe-9809-11e7-9a45-f6c8d7257c96.png)
without:
![no-yakuake](https://user-images.githubusercontent.com/30557958/30358273-1f4e0d82-9809-11e7-8aee-90ec7e3a8150.png)

If you need more information let me know. Thanks.

**Comment by naelstrof** [comment] 2017-09-13 03:46
Try maim v5.4.68, this issue has been fixed in that patch. This issue is a duplicate of #111, though #102 is actually unrelated.

**Comment by enui** [comment] 2017-09-13 03:59
I manually installed v5.4.68 and it is fixed, I see it doesn't have to do with the terminal. I was hesitant to compile due to it not being the version from arch community repo.

Apologies for duplicate issue, thanks for quick response.

**Closed** 2017-09-13 04:00 UTC
Labels: duplicate

**Comment by naelstrof** [comment] 2017-09-13 04:38
No problem! The more issues, the more likely someone will see the solution. Thanks for posting it.
